apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: oreka-eguna-train-0 # Executable ID (max length 64 lowercase-hypen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `text-clf-train-tutorial-1234`
  annotations:
    scenarios.ai.sap.com/description: "Train ABS"
    scenarios.ai.sap.com/name: oreka-eguna-scenario
    executables.ai.sap.com/description: "Train ABS."
    executables.ai.sap.com/name: "oreka-eguna-exec"
    artifacts.ai.sap.com/mytraindataset.kind: "dataset" # Helps in suggesting the kind of inputs that can be attached.
    artifacts.ai.sap.com/modelai.kind: "model" # Helps in suggesting the kind of artifact that can be generated.
  labels:
    scenarios.ai.sap.com/id: oreka-eguna-scenario # Unique ID for the AI scenario.
    ai.sap.com/version: "1.0.1"
spec:
  imagePullSecrets:
    - name: cp-test-docker-registry # Name of Docker regressionistry secret.
  entrypoint: oreka-eguna-training
  arguments:
    parameters: # placeholder for string like inputs
        - name: DT_MAX_DEPTH # identifier local to this workflow
        - name: ALG # identifier local to this workflow
        - name: MIN_PERCENTAGE  # identifier local to this workflow
  templates:
    - name: oreka-eguna-training
      metadata:
        labels:
          ai.sap.com/resourcePlan: starter
      container:
        # URL of Docker image that was previously uploaded to Docker Hub.
        image: docker.io/deliaalene/oreka-eguna:01
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        env:
          - name: ALG # name of the environment variable inside Docker container
            value: "{{workflow.parameters.ALG}}" # value to set from local (to workflow) variable DT_MAX_DEPTH
          - name: DT_MAX_DEPTH # name of the environment variable inside Docker container
            value: "{{workflow.parameters.DT_MAX_DEPTH}}" # value to set from local (to workflow) variable DT_MAX_DEPTH
          - name: MIN_PERCENTAGE # name of the environment variable inside Docker container
            value: "{{workflow.parameters.MIN_PERCENTAGE}}" # value to set from local (to workflow) variable MIN_PERCENTAGE
        args:
          - >
            set -e && echo "---Start Training---" && python /app/src/train.py && ls -lR /app/model && echo "---End Training---"
